# Generated by Django 2.2.3 on 2019-07-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_identificador', models.IntegerField()),
                ('E_codigo', models.IntegerField()),
                ('E_EMAIL', models.CharField(max_length=100)),
            ],
        ),
    ]
