# Generated by Django 2.2.3 on 2019-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_node', models.IntegerField()),
                ('localization', models.CharField(max_length=700)),
                ('solar_radiaton', models.DecimalField(decimal_places=3, max_digits=12)),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
